version: 2

sources:
  - name: erp
    schema: RAW_ADVENTURE_WORKS
    tables:
      - name: SalesOrderHeader  
      - name: SalesOrderDetail
      - name: Product
        description: "Tabela com informações dos produtos."
      - name: CreditCard
        description: "Tabela com informações dos cartões de crédito."
      - name: SalesReason 
        description: "A tabela armazena informações sobre os motivos de venda que podem estar associados a cada pedido de venda."
      - name: Address
      - name: Customer
        description: "A tabela armazena informações sobre os clientes da empresa."
      - name: Person
        description: "Armazena informações com detalhes sobre as pessoas"
      - name: SalesPerson
      - name: Countryregion
      - name: Stateprovince
    